import { useState } from "react";
import Head from "next/head";
import { generateShadeNames } from "@/utils";

import { MainColorBlock, ShadesBlock, Sidebar } from "@/components";

import styles from "./styles.module.scss";

export default function Home() {
  const [mainColor, setMainColor] = useState("#36EAA9");
  const [steps, setSteps] = useState(4);

  const updateMainColor = (e: React.ChangeEvent<HTMLInputElement>) => {
    const color = e.target.value;
    setMainColor(color);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.wrapper}>
        <section className={styles.main}>
          <section className={styles.colorsPreview}>
            <ShadesBlock
              mainColor={mainColor}
              steps={steps}
              direction="darken"
              colorNames={generateShadeNames("darken", steps)}
            />
            <MainColorBlock
              color={mainColor}
              shadesAmount={steps}
              onChange={updateMainColor}
            />
            <ShadesBlock
              mainColor={mainColor}
              steps={steps}
              direction="lighten"
              colorNames={generateShadeNames("lighten", steps)}
            />
          </section>
        </section>

        <Sidebar
          steps={steps}
          onPlusClick={() => setSteps(steps + 1)}
          onMinusClick={() => {
            if (steps > 1) {
              setSteps(steps - 1);
            }
          }}
        />
      </main>
    </>
  );
}
