import { useState } from 'react'
import Head from 'next/head'

import { ColorBlock } from '@/components'

import styles from './styles.module.scss'


export default function Home() {
  const [mainColor, setMainColor] = useState('#000000')

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.wrapper}>

        <section className={styles.main}>
          <section className={styles.colorsPreview}>
            <ColorBlock color={mainColor} />
          </section>

          <section className={styles.controls}>
          </section>
        </section>

        <aside className={styles.sidebar}>
          <section className={styles.sidebarControls}>
          </section>
          <section className={styles.sidebarLinks}>
          </section>
        </aside>

      </main>
    </>
  )
}
